import {StyleSheet} from 'react-native';

import {colors} from '@shared/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.neutral[100],
    alignItems: 'center',
    paddingTop: 20,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 10,
    paddingTop: 15,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.overlay.light,
  },
  modalContent: {
    width: '90%',
    backgroundColor: colors.white,
    padding: 20,
    borderRadius: 10,
    elevation: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.neutral[400],
    padding: 10,
    fontSize: 16,
    borderRadius: 6,
    marginBottom: 10,
  },
  buttonGroup: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 1,
  },
  formTitle: {
    marginTop: 20,
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  title: {
    marginTop: 15,
    fontSize: 22,
    fontWeight: 'bold',
    marginLeft: 30,
    width: '100%',
    textAlign: 'left',
  },
  lastRecordContainer: {
    width: '90%',
    padding: 10,
    backgroundColor: colors.white,
    borderRadius: 10,
    marginTop: 15,
    marginBottom: 15,
    elevation: 2,
    shadowColor: colors.shadow,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
  },
  placeholderContainer: {
    width: '90%',
    padding: 20,
    backgroundColor: colors.neutral[50],
    borderRadius: 10,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: colors.neutral[500],
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  placeholderText: {
    fontSize: 16,
    color: colors.neutral[700],
    textAlign: 'center',
    lineHeight: 24,
  },
  exportButtonContainer: {
    width: '90%',
    marginTop: 10,
    alignItems: 'center',
  },
});
